<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_here</name>
   <tag></tag>
   <elementGuidId>7d8efbc0-216e-463b-bc91-8d4820509345</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://s-www.cengage.com/shop/mycart?token=20F88DC8756D52E26F92AD53C6626661AB17FA127046F5CE5F5852521F9234135A5CD34DF507FFF340B84B28B3D44E490D1DA0632866BC1F54B529E381BB2DC92207F0D7AE3A9727</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>here</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;mod_js mod_cookies mod_no-ie8compat mod_flexbox mod_flexboxlegacy mod_no-flexboxtweener mod_flexwrap ng-scope&quot;]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;ceng-eForms ceng-eForms--modal ng-scope&quot;]/div[@class=&quot;ceng-eForms_modal ceng-studentProductModal&quot;]/div[@class=&quot;ceng-studentProductModal_inner&quot;]/div[@class=&quot;ceng-studentProductModal_body&quot;]/div[@class=&quot;ceng-studentProductModal_rtf ng-binding&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
