<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TextbookeBookfrom30.99</name>
   <tag></tag>
   <elementGuidId>cddae68b-009d-41b3-89cb-436b0819eeb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;mod_js mod_cookies mod_no-ie8compat mod_flexbox mod_flexboxlegacy mod_no-flexboxtweener mod_flexwrap ng-scope&quot;]/body[@class=&quot;ng-scope&quot;]/main[@class=&quot;ceng-pageContents ceng-pageContents--default&quot;]/div[@class=&quot;ceng-studentProduct ceng-studentProduct--details ng-scope&quot;]/div[@class=&quot;ceng-studentProduct_section ceng-studentProduct_section--overview ceng-studentProduct_section--blue&quot;]/student-product-pricing[@class=&quot;ng-scope&quot;]/div[@class=&quot;ceng-studentProductPricing ceng-studentProductPricing--default&quot;]/div[@class=&quot;ceng-studentProductPricing_tabs js-student-product__pricing-tabs&quot;]/div[@class=&quot;ceng-studentProductPricing_tab   js-student-product__pricing-tab&quot;]/a[@class=&quot;ceng-studentProductPricing_entryTab&quot;][count(. | //a[@href = 'javascript:;' and @class = 'ceng-studentProductPricing_entryTab' and (text() = 'Textbook/eBook' or . = 'Textbook/eBook')]) = count(//a[@href = 'javascript:;' and @class = 'ceng-studentProductPricing_entryTab' and (text() = 'Textbook/eBook' or . = 'Textbook/eBook')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ceng-studentProductPricing_entryTab</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Textbook/eBook</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;mod_js mod_cookies mod_no-ie8compat mod_flexbox mod_flexboxlegacy mod_no-flexboxtweener mod_flexwrap ng-scope&quot;]/body[@class=&quot;ng-scope&quot;]/main[@class=&quot;ceng-pageContents ceng-pageContents--default&quot;]/div[@class=&quot;ceng-studentProduct ceng-studentProduct--details ng-scope&quot;]/div[@class=&quot;ceng-studentProduct_section ceng-studentProduct_section--overview ceng-studentProduct_section--blue&quot;]/student-product-pricing[@class=&quot;ng-scope&quot;]/div[@class=&quot;ceng-studentProductPricing ceng-studentProductPricing--default&quot;]/div[@class=&quot;ceng-studentProductPricing_tabs js-student-product__pricing-tabs&quot;]/div[@class=&quot;ceng-studentProductPricing_tab   js-student-product__pricing-tab&quot;]/a[@class=&quot;ceng-studentProductPricing_entryTab&quot;]</value>
   </webElementProperties>
</WebElementEntity>
