<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Bundle</name>
   <tag></tag>
   <elementGuidId>26e5c57b-43a8-41c4-bbbb-b488ebd7de60</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bundle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;mod_js mod_cookies mod_no-ie8compat mod_flexbox mod_flexboxlegacy mod_no-flexboxtweener mod_flexwrap ng-scope&quot;]/body[@class=&quot;ng-scope&quot;]/main[@class=&quot;ceng-pageContents ceng-pageContents--default&quot;]/div[@class=&quot;ceng-studentProduct ceng-studentProduct--details ng-scope&quot;]/div[@class=&quot;ceng-studentProduct_section ceng-studentProduct_section--overview ceng-studentProduct_section--blue&quot;]/student-product-pricing[@class=&quot;ng-scope&quot;]/div[@class=&quot;ceng-studentProductPricing ceng-studentProductPricing--default&quot;]/div[@class=&quot;ceng-studentProductPricing_tabs js-student-product__pricing-tabs&quot;]/div[@class=&quot;ceng-studentProductPricing_tab js-student-product__pricing-tab is-active&quot;]/a[@class=&quot;ceng-studentProductPricing_entryTab&quot;]/span[@class=&quot;ceng-studentProductPricing_entryTabLabel&quot;]/em[1]</value>
   </webElementProperties>
</WebElementEntity>
