<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Students</name>
   <tag></tag>
   <elementGuidId>0fe464db-74ed-44fe-9080-4e04682018e4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://s-www.cengage.com/students/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cookie</name>
      <type>Main</type>
      <value>Student</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-header-type</name>
      <type>Main</type>
      <value>Student</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Students</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ceng-header&quot;)/div[@class=&quot;ceng-headerNav&quot;]/div[@class=&quot;ceng-headerNav_navs&quot;]/div[@class=&quot;ceng-headerNavMain&quot;]/nav[@class=&quot;ceng-headerNavMain_training&quot;]/ul[@class=&quot;ceng-headerNavMain_nav&quot;]/li[@class=&quot;ceng-headerNavMain_navItem&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
